POST http://localhost:8080/odt-actions-test HTTP/1.1
content-type: application/json;charset=UTF-8
accept: application/json
X-Session-Identifier: 1xxx-xxxx-xxxx-xxxx

{
    "actions":[
        "TestForm1,btnClick",
        "TestForm1,btnClick",
        "TestForm1,select,3",
        "TestForm1,dialog",
        "DIALOG_OPEN",
        "TestForm2,select,2",
        "TestForm2,counter,",
        "TestForm2,counter,3",
        "TestForm2,btnClick"
    ]
}
